version: '3'

volumes:
  production_traefik: {}

services:
  fastapi:
    build:
      context: .
      dockerfile: ./compose/production/fastapi/Dockerfile
    image: fastapi_production
    command: /start

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: fastapi_production_traefik
    depends_on:
      - fastapi
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"