version: '3'

services:
  fastapi:
    build:
      context: .
      dockerfile: ./compose/production/fastapi/Dockerfile
    image: fastapi_production
    command: /start
    env_file:
      - ./.envs/.production/.traefik
    labels:
      - traefik.enable=true
      - traefik.http.services.api.loadbalancer.server.port=5000
      - traefik.routers.api-http.entrypoint=http
      - traefik.routers.api-http.rule=Host(`${FASTAPI_HOSTNAME}`)
      - traefik.docker.network=traefik
      - traefik.http.routers.api-https.entrypoints=https
      - traefik.http.routers.api-https.rule=Host(`${FASTAPI_HOSTNAME}`)
      - traefik.http.routers.api-https.tls=true
      - traefik.http.routers.api-https.tls.certresolver=le
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      - traefik.http.routers.api-http.middlewares=https-redirect
    networks:
      - traefik
    depends_on:
      - traefik


  traefik:
    image: traefik:v2.6
    ports:
      - "80:80"
      - "443:443"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-public-certificates:/certificates
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --certificatesresolvers.le.acme.email=${USER_EMAIL}
      - --certificatesresolvers.le.acme.storage=/certificates/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --accesslog
      - --log
      - --api
    env_file:
      - ./.envs/.production/.traefik
    networks:
      - traefik

volumes:
  traefik-public-certificates:

networks:
  traefik:
    driver: bridge